[workspace]
members = [
    "exercise-1",
    "exercise-2",
    "exercise-3",
    "exercise-4",
    "fuzzer-options"
]
exclude = [ "LibAFL", "AFLTriage" ]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true
